(()=>{const KEY="creatorXBrandProfile";
function getProfile(){try{return JSON.parse(localStorage.getItem(KEY)||"null")}catch{return null}}
function initials(name,email){const s=(name||email||"U").trim();return s.split(/\\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase()}
function header(){const old=document.querySelector("body>header");if(old)old.remove();document.querySelectorAll("body>.top,body>main>.top").forEach(e=>e.classList.add("legacy-hidden"));
const current=location.pathname.split("/").pop()||"index.html";const nav=[["index.html","Home"],["about.html","About"],["services.html","Services"],["contact.html","Contact"]];
const profile=getProfile();
const account=profile?'<div class="site-profile"><button class="site-profile-btn" id="siteProfileBtn"><span class="site-avatar">'+initials(profile.name,profile.email)+'</span>Profile</button><div class="site-profile-menu" id="siteProfileMenu"><button id="siteSignOut">Sign out</button></div></div>':'<a class="site-account" href="#" data-auth="signin">Sign in</a><a class="site-account signup" href="#" data-auth="signup">Sign up</a>';
const links=nav.map(([href,label])=>'<a href="'+href+'"'+(current===href?' class="active"':'')+'>'+label+'</a>').join("");
document.body.insertAdjacentHTML("afterbegin",'<header class="site-header"><nav class="site-nav"><a class="site-logo" href="index.html">Creator <span>X</span> Brand</a><div class="site-nav-right">'+account+'<button class="site-menu-btn" id="siteMenuBtn" aria-label="Open menu" aria-expanded="false"><span class="site-menu-icon"></span></button></div><div class="site-drawer" id="siteDrawer">'+links+'</div></nav></header>');
}
function modal(){document.body.insertAdjacentHTML("beforeend",'<div class="site-auth-modal" id="siteAuthModal" aria-hidden="true"><div class="site-auth-box"><div class="site-auth-head"><h2 id="siteAuthTitle">Sign in</h2><button class="site-auth-close" id="siteAuthClose" aria-label="Close">×</button></div><div class="site-auth-tabs"><button class="site-auth-tab active" data-mode="signin">Sign in</button><button class="site-auth-tab" data-mode="signup">Sign up</button></div><form class="site-auth-form" id="siteAuthForm"><div id="siteNameWrap" style="display:none"><label for="siteName">Name</label><input id="siteName" autocomplete="name" placeholder="Your name"></div><label for="siteEmail">Email</label><input id="siteEmail" type="email" required autocomplete="email" placeholder="you@example.com"><label for="sitePassword">Password</label><input id="sitePassword" type="password" required autocomplete="current-password" placeholder="Your password"><button class="site-auth-submit" type="submit" id="siteAuthSubmit">Sign in</button></form><p class="site-auth-note">This prototype keeps the profile state on this device. A real launch needs server-side authentication and secure session handling.</p></div></div>')}
function init(){header();modal();const drawer=document.getElementById("siteDrawer"),menu=document.getElementById("siteMenuBtn");menu.addEventListener("click",e=>{e.stopPropagation();const open=drawer.classList.toggle("open");menu.setAttribute("aria-expanded",open)});document.addEventListener("click",e=>{if(!e.target.closest("#siteMenuBtn")&&!e.target.closest("#siteDrawer"))drawer.classList.remove("open")});
const modalEl=document.getElementById("siteAuthModal"),close=document.getElementById("siteAuthClose"),title=document.getElementById("siteAuthTitle"),nameWrap=document.getElementById("siteNameWrap"),name=document.getElementById("siteName"),email=document.getElementById("siteEmail"),pass=document.getElementById("sitePassword"),submit=document.getElementById("siteAuthSubmit");let mode="signin";
function setMode(m){mode=m;title.textContent=m==="signup"?"Create your account":"Sign in";nameWrap.style.display=m==="signup"?"block":"none";name.required=m==="signup";submit.textContent=m==="signup"?"Create account":"Sign in";document.querySelectorAll(".site-auth-tab").forEach(x=>x.classList.toggle("active",x.dataset.mode===m));pass.autocomplete=m==="signup"?"new-password":"current-password"}
function open(m){setMode(m);modalEl.classList.add("open");modalEl.setAttribute("aria-hidden","false");email.focus()}
document.querySelectorAll("[data-auth]").forEach(x=>x.addEventListener("click",e=>{e.preventDefault();open(x.dataset.auth)}));
document.querySelectorAll(".site-auth-tab").forEach(x=>x.addEventListener("click",()=>setMode(x.dataset.mode)));
close.addEventListener("click",()=>modalEl.classList.remove("open"));modalEl.addEventListener("click",e=>{if(e.target===modalEl)modalEl.classList.remove("open")});
document.getElementById("siteAuthForm").addEventListener("submit",e=>{e.preventDefault();localStorage.setItem(KEY,JSON.stringify({name:name.value.trim(),email:email.value.trim(),signedIn:true}));modalEl.classList.remove("open");location.reload()});
const profileBtn=document.getElementById("siteProfileBtn");if(profileBtn){const pm=document.getElementById("siteProfileMenu");profileBtn.addEventListener("click",e=>{e.stopPropagation();pm.classList.toggle("open")});document.addEventListener("click",e=>{if(!e.target.closest(".site-profile"))pm.classList.remove("open")});document.getElementById("siteSignOut").addEventListener("click",()=>{localStorage.removeItem(KEY);location.reload()})}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init()})();